# -*- coding: utf-8 -*-
"""ocr test

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZFKbvrcpHbTNC8Qpbz2idQHt908x69WM
"""

!pip install easyocr --no-deps

from google.colab import drive
drive.mount('/content/gdrive')

img_path = "/content/gdrive/My Drive/pic3.jpg"

import PIL
from PIL import ImageDraw
im = PIL.Image.open(img_path)
im

pip install git+git://github.com/jaidedai/easyocr.git

import easyocr
reader = easyocr.Reader(['en','en'])

# Doing OCR. Get bounding boxes.
bounds = reader.readtext(img_path)
bounds

def draw_boxes(image, bounds, color='red', width=2):
    draw = ImageDraw.Draw(image)
    for bound in bounds:
        p0, p1, p2, p3 = bound[0]
        draw.line([*p0, *p1, *p2, *p3, *p0], fill=color, width=width)
    return image

draw_boxes(im, bounds)

